twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        CategoriesService: '@App\Service\CategoriesService'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
